In [4]:
import tensorflow as tf
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers

print(tf.__version__)

2.4.0


## One hot encoding

In [5]:
h = [1,0,0,0]
e = [0,1,0,0]
l = [0,0,1,0]
o = [0,0,0,1]

.

## Unfolding to n sequences : 4 input-dim, 2 hidden_size

In [19]:
x_data = np.array([[h]], dtype=np.float32)

hidden_size = 2
cell = layers.SimpleRNNCell(units=hidden_size)
rnn = layers.RNN(cell, return_sequences=True, return_state=True)
outputs, states = rnn(x_data)

outputs.numpy(), states.numpy()

(array([[[ 0.49136233, -0.0588884 ]]], dtype=float32),
 array([[ 0.49136233, -0.0588884 ]], dtype=float32))

In [13]:
print('x_data:{}, shape:{}'.format(x_data, x_data.shape))
print('outputs:{}, shape:{}'.format(outputs, outputs.shape)) # 전체 hidden sequence 
print('states:{}, shape:{}'.format(states, states.shape)) # 마지막 hidden sequence

x_data:[[[1. 0. 0. 0.]]], shape:(1, 1, 4)
outputs:[[[-0.3577779  0.5476667]]], shape:(1, 1, 2)
states:[[-0.3577779  0.5476667]], shape:(1, 2)


.

## Batching Input : 4 input-dim, 2 hidden_size, 5 sequences

In [16]:
x_data = np.array([[h,e,l,l,o]], dtype=np.float32)

hidden_size = 2
cell = layers.SimpleRNNCell(units=hidden_size)
rnn = layers.RNN(cell, return_sequences=True, return_state=True)
outputs, states = rnn(x_data)

In [15]:
print('x_data:{}, shape:{}'.format(x_data, x_data.shape))
print('outputs:{}, shape:{}'.format(outputs, outputs.shape)) # 전체 hidden sequence 
print('states:{}, shape:{}'.format(states, states.shape)) # 마지막 hidden sequence

x_data:[[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]], shape:(1, 5, 4)
outputs:[[[-0.34691697 -0.51700586]
  [ 0.89644384  0.8568704 ]
  [-0.598336   -0.9110191 ]
  [ 0.7746647   0.01344689]
  [ 0.75317234 -0.72490406]]], shape:(1, 5, 2)
states:[[ 0.75317234 -0.72490406]], shape:(1, 2)


.

## One Cell : 4 input-dim, 2 hidden_size, 5 sequences, 3 batches

In [17]:
x_data = np.array([[h,e,l,l,o],
                  [e,o,l,l,l],
                  [l,l,e,e,l]], dtype=np.float32)

hidden_size = 2
cell = layers.SimpleRNNCell(units=hidden_size)
rnn = layers.RNN(cell, return_sequences=True, return_state=True)
outputs, states = rnn(x_data)

In [18]:
print('x_data:{}, shape:{}'.format(x_data, x_data.shape))
print('outputs:{}, shape:{}'.format(outputs, outputs.shape)) # 전체 hidden sequence 
print('states:{}, shape:{}'.format(states, states.shape)) # 마지막 hidden sequence

x_data:[[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]]

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]]], shape:(3, 5, 4)
outputs:[[[-0.5967173  -0.56061196]
  [ 0.1964272   0.31207407]
  [-0.19292851  0.52831924]
  [-0.5531037   0.61245817]
  [-0.3269624  -0.31911865]]

 [[ 0.216059   -0.45869324]
  [ 0.745684   -0.12447296]
  [ 0.4630517   0.46512708]
  [-0.11636415  0.28265595]
  [-0.37502918  0.6810208 ]]

 [[-0.11093757  0.7383612 ]
  [-0.6135869   0.46753174]
  [-0.49623552 -0.3693638 ]
  [ 0.132778    0.11642508]
  [-0.10057387  0.6472699 ]]], shape:(3, 5, 2)
states:[[-0.3269624  -0.31911865]
 [-0.37502918  0.6810208 ]
 [-0.10057387  0.6472699 ]], shape:(3, 2)
